all:
  hosts:
    node1:
      ansible_host: 10.54.108.210
      ip: 10.54.108.210
      access_ip: 10.54.108.210
    node2:
      ansible_host: 10.54.108.212
      ip: 10.54.108.212
      access_ip: 10.54.108.212
    node3:
      ansible_host: 10.54.108.213
      ip: 10.54.108.213
      access_ip: 10.54.108.213
    node4:
      ansible_host: 10.54.108.214
      ip: 10.54.108.214
      access_ip: 10.54.108.214
    node5:
      ansible_host: 10.54.108.215
      ip: 10.54.108.215
      access_ip: 10.54.108.215
    node6:
      ansible_host: 10.54.108.216
      ip: 10.54.108.216
      access_ip: 10.54.108.216
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
